### ISSUE TITLE
Revisit structure of deployment docs

### ISSUE THREAD

**Issue by TyDunn** [RasaHQ/helm-charts#31]
We need to revisit how we recommend deploying Rasa Open Source, Rasa X, and Rasa Action Server in the docs.

New production recommendation: deploy with [new Rasa Open Source helm chart](https://artifacthub.io/packages/helm/rasa/rasa) and [forward events to Rasa X](https://rasa.com/docs/rasa-x/installation-and-setup/deploy#connect-an-existing-deployment) (using helm chart that is coming soon)

Open questions
- [ ] When do we nudge people to set up Rasa X?
- [ ] How do we structure the documentation with the separate deployments?
- [ ] What do we do with local mode?

@tmbo and I discussed removing the Rasa X installation from [here](https://rasa.com/docs/rasa/next/how-to-deploy#recommended-deployment-methods), making the helm charts the default deployment method for the production use case. However, it's not clear where we nudge people to set up Rasa X.

For Rasa X / Enterprise, we also discussed structuring the documentation on deployment [similar to gitlab](https://docs.gitlab.com/ee/install/#choose-the-installation-method) with the two installation methods we'll have there: 
- helm charts
- single line install

**Comment by tczekajlo** [comment]
@RASADSA I think we can close it, right?

**Comment by andreoid** [comment]
Closing this off, we don't need to track this as an issue.
This is going to be a new initiative being led by Melinda.
