### ISSUE TITLE
nil pointer evaluating interface when upper level doesn't exist in .Values

### ISSUE THREAD

**Issue by kaiogu** [RasaHQ/helm-charts#40]
I get the following error when enabling `rabbitmq` without having a `.Values.rabbitmq.service` section in `values.yaml`:

```
Error: UPGRADE FAILED: template: rasa/templates/deployment.yaml:107:14: executing "rasa/templates/deployment.yaml" at <include "rasa.containers.env" .>: error calling include: template: rasa/templates/_containers-env.yaml:16:3: executing "rasa.containers.env" at <include "rasa-common.rabbitmq.envs" .>: error calling include: template: rasa/charts/rasa-common/templates/_rabbitmq.tpl:30:24: executing "rasa-common.rabbitmq.port" at <.Values.rabbitmq.service.port>: nil pointer evaluating interface {}.port
```

This is a known [helm issue](https://github.com/helm/helm/issues/8026).

The offending lines in this case:

https://github.com/RasaHQ/helm-charts/blob/c792f05385615d7e07a9f83ae3735f4ba0984f61/charts/rasa-common/templates/_rabbitmq.tpl#L26-L31

As it is implemented now, the coalesce is all but useless. This can be worked around in the user side, if an empty `.Values.rabbitmq.service` is defined, but that almost defeats the purpose of a coalesce/default.

On the side of the Chart, the following line would fix the problem:

```
{{- default 5672 ((.Values.rabbitmq).service).port -}}
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @jupyterjazz will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
