### ISSUE TITLE
In JSON schema `fullnameOverride` is defined as type: null - means it cannot be overwritten with string

### ISSUE THREAD

**Issue by SeanCondon** [RasaHQ/helm-charts#69]
When I try to deploy the Rasa Helm chart and set the `fullnameOverride` in my values file, I get an error:
```bash
helm -n mynamespace install --dry-run --generate-name rasa/rasa --set fullnameOverride=test1
```
gives
```
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
rasa:
- fullnameOverride: Invalid type. Expected: null, given: string
```

It seeps Helm 3 applies the JSON Schema to validate the `values.yaml`, and because this attribute is marked as type: null in the `values.schema.json`, it does not seem to be possible to override it with a string value.

Please let me know if you have any workaround

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @ancalita will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by SeanCondon** [comment]
Thanks for fixing this so quickly
