### ISSUE TITLE
Network policy for redis points to postgres port

### ISSUE THREAD

**Issue by nyejon** [RasaHQ/helm-charts#74]
Hi,

The network policy for redis points to the postgres port:

https://github.com/RasaHQ/helm-charts/blob/c93efed700651f80e1e90e8b8b7a09793957f360/charts/rasa/templates/network-policy/rasa-bot-redis.yaml#L13-L25

Can you please fix this to use the redis port value from the values file.

**Comment by nyejon** [comment]
The way around this is to disable the NP generated by the rasa-oss chart and use the NP from Rasa-X.

You can use the NP from Rasa-X by adding the following label to the podLabels in the values file.

```
podLabels:
  app.kubernetes.io/component: rasa-production
```

or 

```
podLabels:
  app.kubernetes.io/component: rasa-worker
```

**Comment by HotThoughts** [comment]
Hi @nyejon, thanks for reporting this. The fix is on the way 🏃🏻 .
