### ISSUE TITLE
Duckling endpoint not passed to pod when external is True and an external URL is provided

### ISSUE THREAD

**Issue by nyejon** [RasaHQ/helm-charts#76]
https://github.com/RasaHQ/helm-charts/blob/e7e72f4a3333cb42430c0f49d001cb7d03fdaf74/charts/rasa/templates/helpers/_duckling.tpl#L5

This results in the following:
if false or (true and (not true)) resulting in false. We need this to be true when external = true and external url = true.

{{- if or .Values.duckling.install (and .Values.duckling.external.enabled .Values.duckling.external.url) -}} would be better.

This means the duckling endpoint is not provided to the pod here:

https://github.com/RasaHQ/helm-charts/blob/e7e72f4a3333cb42430c0f49d001cb7d03fdaf74/charts/rasa/templates/_containers-env.yaml#L21-L23

**Comment by sara-tagger** [comment]
Thanks for the issue, @yennycheung will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by nyejon** [comment]
One can get around this issue by manually adding to the envs of the rasa pod.:
```
- name: “RASA_DUCKLING_HTTP_URL”
   value: “http://{duckling_service}:8000”
```
